version: '3.8'

services:
  db:
    container_name: fm_vanilla_go
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movies_db
    ports:
        - "5433:5432"
    volumes:
      - "./.db/postgres-data:/var/lib/postgresql/data"
    restart: unless-stopped
