// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"
)

type Actor struct {
	ID        int32
	FirstName string
	LastName  string
	ImageUrl  sql.NullString
}

type Genre struct {
	ID   int32
	Name string
}

type Keyword struct {
	ID   int32
	Word string
}

type Movie struct {
	ID          int32
	TmdbID      sql.NullInt32
	Title       string
	Tagline     sql.NullString
	ReleaseYear sql.NullInt32
	Overview    sql.NullString
	Score       sql.NullFloat64
	Popularity  sql.NullFloat64
	Language    sql.NullString
	PosterUrl   sql.NullString
	TrailerUrl  sql.NullString
}

type MovieCast struct {
	MovieID int32
	ActorID int32
}

type MovieGenre struct {
	MovieID int32
	GenreID int32
}

type MovieKeyword struct {
	MovieID   int32
	KeywordID int32
}

type User struct {
	ID             int32
	Name           string
	Email          string
	PasswordHashed string
	LastLogin      *time.Time
	TimeCreated    time.Time
	TimeConfirmed  *time.Time
	TimeDeleted    *time.Time
}

type UserMovie struct {
	UserID       int32
	MovieID      int32
	RelationType string
	TimeAdded    time.Time
}
